# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VesicleViewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VesicleViewer(object):
    def setupUi(self, VesicleViewer):
        VesicleViewer.setObjectName("VesicleViewer")
        VesicleViewer.resize(788, 882)
        self.centralWidget = QtWidgets.QWidget(VesicleViewer)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 577))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainGraphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.mainGraphicsView.setAutoFillBackground(False)
        self.mainGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mainGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mainGraphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.mainGraphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.mainGraphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.mainGraphicsView.setObjectName("mainGraphicsView")
        self.verticalLayout_3.addWidget(self.mainGraphicsView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalSlider_int_low = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_int_low.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_int_low.setObjectName("horizontalSlider_int_low")
        self.gridLayout_4.addWidget(self.horizontalSlider_int_low, 0, 1, 1, 1)
        self.spinBox_int_low = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.spinBox_int_low.setObjectName("spinBox_int_low")
        self.gridLayout_4.addWidget(self.spinBox_int_low, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.spinBox_int_high = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.spinBox_int_high.setObjectName("spinBox_int_high")
        self.gridLayout_4.addWidget(self.spinBox_int_high, 2, 0, 1, 1)
        self.horizontalSlider_int_high = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_int_high.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_int_high.setObjectName("horizontalSlider_int_high")
        self.gridLayout_4.addWidget(self.horizontalSlider_int_high, 2, 1, 1, 1)
        self.checkBox_is_log = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_is_log.setObjectName("checkBox_is_log")
        self.gridLayout_4.addWidget(self.checkBox_is_log, 0, 5, 1, 1)
        self.pushButton_autoscale = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_autoscale.setObjectName("pushButton_autoscale")
        self.gridLayout_4.addWidget(self.pushButton_autoscale, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBox_frame = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_frame.setMaximum(999999999)
        self.spinBox_frame.setObjectName("spinBox_frame")
        self.horizontalLayout_3.addWidget(self.spinBox_frame)
        self.label_frame = QtWidgets.QLabel(self.centralWidget)
        self.label_frame.setObjectName("label_frame")
        self.horizontalLayout_3.addWidget(self.label_frame)
        self.spinBox_step = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_step.setMaximum(999999999)
        self.spinBox_step.setProperty("value", 1)
        self.spinBox_step.setObjectName("spinBox_step")
        self.horizontalLayout_3.addWidget(self.spinBox_step)
        self.label_step = QtWidgets.QLabel(self.centralWidget)
        self.label_step.setObjectName("label_step")
        self.horizontalLayout_3.addWidget(self.label_step)
        self.doubleSpinBox_fps = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_fps.setMaximum(100.0)
        self.doubleSpinBox_fps.setProperty("value", 25.0)
        self.doubleSpinBox_fps.setObjectName("doubleSpinBox_fps")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_fps)
        self.label_fps = QtWidgets.QLabel(self.centralWidget)
        self.label_fps.setObjectName("label_fps")
        self.horizontalLayout_3.addWidget(self.label_fps)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_h5path = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_h5path.setEditable(True)
        self.comboBox_h5path.setObjectName("comboBox_h5path")
        self.comboBox_h5path.addItem("")
        self.comboBox_h5path.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_h5path)
        self.pushButton_h5groups = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_h5groups.sizePolicy().hasHeightForWidth())
        self.pushButton_h5groups.setSizePolicy(sizePolicy)
        self.pushButton_h5groups.setObjectName("pushButton_h5groups")
        self.horizontalLayout_6.addWidget(self.pushButton_h5groups)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageSlider = QtWidgets.QSlider(self.centralWidget)
        self.imageSlider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.imageSlider.setMouseTracking(True)
        self.imageSlider.setAutoFillBackground(False)
        self.imageSlider.setMaximum(100)
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setInvertedAppearance(False)
        self.imageSlider.setInvertedControls(False)
        self.imageSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.imageSlider.setObjectName("imageSlider")
        self.horizontalLayout_2.addWidget(self.imageSlider)
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setCheckable(False)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_2.addWidget(self.playButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_video = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_video.setText("")
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.horizontalLayout.addWidget(self.lineEdit_video)
        self.pushButton_video = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_video.setObjectName("pushButton_video")
        self.horizontalLayout.addWidget(self.pushButton_video)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        VesicleViewer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(VesicleViewer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 788, 22))
        self.menuBar.setObjectName("menuBar")
        VesicleViewer.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(VesicleViewer)
        self.mainToolBar.setObjectName("mainToolBar")
        VesicleViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.toolBar = QtWidgets.QToolBar(VesicleViewer)
        self.toolBar.setObjectName("toolBar")
        VesicleViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(VesicleViewer)
        QtCore.QMetaObject.connectSlotsByName(VesicleViewer)

    def retranslateUi(self, VesicleViewer):
        _translate = QtCore.QCoreApplication.translate
        VesicleViewer.setWindowTitle(_translate("VesicleViewer", "HDF5VideoPlayer"))
        self.checkBox_is_log.setText(_translate("VesicleViewer", "log-scale"))
        self.pushButton_autoscale.setText(_translate("VesicleViewer", "AutoScale"))
        self.label_frame.setText(_translate("VesicleViewer", "Frame"))
        self.label_step.setText(_translate("VesicleViewer", "Step Size"))
        self.label_fps.setText(_translate("VesicleViewer", "FPS display"))
        self.comboBox_h5path.setItemText(0, _translate("VesicleViewer", "/mask"))
        self.comboBox_h5path.setItemText(1, _translate("VesicleViewer", "/full_data"))
        self.pushButton_h5groups.setText(_translate("VesicleViewer", "Update Groups"))
        self.playButton.setText(_translate("VesicleViewer", "Play"))
        self.pushButton_video.setText(_translate("VesicleViewer", "Select File"))
        self.toolBar.setWindowTitle(_translate("VesicleViewer", "toolBar"))

